background_estimator:
  estimator: MOG2

paths:
  annotations: '../dataset/ai_challenge_s03_c010-full_annotation.xml'
  video: '../dataset/AICity_data/train/S03/c010/vdo.avi'
  extracted_frames: '../dataset/w2_t1_frames'

