paths:
  annotations: '../../dataset/ai_challenge_s03_c010-full_annotation.xml'
  video: '../../dataset/AICity_data/train/S03/c010/vdo.avi'
  rcnn: '../../dataset/AICity_data/train/S03/c010/det/det_mask_rcnn.txt'
  ssd: '../../dataset/AICity_data/train/S03/c010/det/det_ssd512.txt'
  yolo: '../../dataset/AICity_data/train/S03/c010/det/det_yolo3.txt'

settings:
  plot_random_annotation: True
  model: yolo

noise:
  res: [1920, 1080]
  pos: False
  max_pxdisplacement: 50
  size: True
  max_scale: 1.5
  min_scale: 0.1
  removebbox: False
  ratio_removebbox: 0.2
  addbbox: False
  ratio_addbbox: 0.2
