lk_flow_path: '../dataset/results/'
gt_flow_path: '../dataset/data_stereo_flow/training/flow_noc/'
img_path: '../dataset/data_stereo_flow/training/colored_0/'

img_1: 'LKflow_000045_10.png'
img_2: '000157_10.png'