paths:
  annotations: '../../dataset/ai_challenge_s03_c010-full_annotation.xml'
  video: '../../dataset/AICity_data/train/S03/c010/vdo.avi'
  rcnn: '../../dataset/AICity_data/train/S03/c010/det/det_mask_rcnn.txt'
  ssd: '../../dataset/AICity_data/train/S03/c010/det/det_ssd512.txt'
  yolo: '../../dataset/AICity_data/train/S03/c010/det/det_yolo3.txt'

settings:
  plot_random_annotation: True
  model: rcnn
  save_all_frames_plots: False
noise:
  res: [1920, 1080]
  random: True
  pos: True
  max_pxdisplacement: [0, 10, 25, 50, 75, 100]
  size: True
  max_scale: [0.125, 0.25, 0.5, 1., 2., 4.]
  min_scale: 1.0
  removebbox: True
  ratio_removebbox: [0., 0.2, 0.4, 0.6, 0.8, 0.9]
  addbbox: True
  ratio_addbbox: [0., 0.2, 0.4, 0.6, 0.8, 0.9]
