device: "cuda"

val_path: "data/reid2/val"
data_path: "data/detection/val"

embedder_size: 256

trunk_weights_path: models/reid/trunk_best15.pth
embedder_weights_path: models/reid/embedder_best15.pth
save_tracking_videos: False
save_tracking: False
save_tracking_path: "data/tracking"

th: 0.8 # euclidean distance threshold to determine same car

