model: models/yolov8n.pt
train_yolo : configs/train_yolo.yaml
epochs: 40
#Hyperparameters
param_grid: {'batch_size': [64],
             'image_size' : [512],
             'learning_rate': [0.003]}
#Number of iterations for random search (use n=1 in case you don't want to use random search)
n: 1