paths:
  kitti: '../dataset/results_opticalflow_kitti/results'
  gt: '../dataset/data_stereo_flow/training/flow_noc'
  block_matching: 'dataset/results_block_matching'
  block_matching2: 'dataset/results_block_matching2'
  farneback: 'dataset/results_farneback'
  sequence45: "../dataset/data_stereo_flow/training/image_1"
evaluate_own_OF: True
OS_system: "linux"
OF_method: "block_matching2"
