model:
  use_gt: False
  first_frame: 0
  last_frame: 400
  save_gt_tracking_MOT: False
visualization:
  show_detection: True
  save: False

paths:
  annotations: '../dataset/aic19-track1-mtmc-train/train/S03/c011/gt/gt.txt'
  video: '../dataset/aic19-track1-mtmc-train/train/S03/c011/vdo.avi'
  extracted_frames: '../dataset/w4_frames/SO3/c011'
  detected_bboxes: '../dataset/aic19-track1-mtmc-train/train/S03/c011/det/det_yolo3.txt'
  output: '../output/task2/YOLOv3_S03'